
version: '3'

services:
  redis:  
    image: redis:6.2.14-alpine
    pull_policy: always
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - default

  garnet:
      image: 'ghcr.io/microsoft/garnet'
      ulimits:
        memlock: -1
      ports:
        - "7379:6379"
      networks:
        - default

networks:
  default:
    driver: bridge