name: dotnet package

on: [push]

env:
  TARGET_PROJECT: ./src/ServiceCache/ServiceCache.csproj
  PKG_DEST_FOLDER: ./src/ServiceCache/bin/Release/*.nupkg
  TARGET_TEST_PROJECT: ./test/ServiceCache.Test/ServiceCache.Test.csproj


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x

      - name: Install dependencies
        run: dotnet restore $TARGET_PROJECT

      - name: Build
        run: dotnet build $TARGET_PROJECT

      - name: Create the package
        run: dotnet pack --configuration Release $TARGET_PROJECT

      - name: Publish the package to GPR
        run: dotnet nuget push $PKG_DEST_FOLDER