name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
      - name: Install dependencies
        run: dotnet restore ./src/ServiceCache/ServiceCache.csproj
      - name: Build
        run: dotnet build ./src/ServiceCache/ServiceCache.csproj
      - name: Test with dotnet
        run: dotnet test ./test/ServiceCache.Test/ServiceCache.Test.csproj --logger trx"
      - name: Create the package
        run: dotnet pack --configuration Release ./src/ServiceCache/ServiceCache.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/ServiceCache/bin/Release/*.nupkg